In [4]:
import pandas as pd
from datascience import *
import numpy as np

In [9]:
# cria um array com idades
arr_idades = np.arange(9, 60)
arr_idades

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [10]:
tb_idades = Table().with_column('idade', arr_idades)
tb_idades

idade
9
10
11
12
13
14
15
16
17
18
... (41 rows omitted)

### Predicates
#### Predicados na verdade são funções que podem ser passadas no where

In [13]:
ainda_jovem = are.between(35,41)
ainda_jovem

In [14]:
tb_idades.where('idade', ainda_jovem)

idade
35
36
37
38
39
40

### podemos passar um predicate para um apply

In [15]:
# cria outro predicado
adolescente = are.between(12, 16)

In [16]:
tb_idades.apply(adolescente, 'idade')

array([False, False, False,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [17]:
tb_idades.where('idade', adolescente)

idade
12
13
14
15

### Random Selection

In [18]:
# with replacenent (independent events)
np.random.choice

<function RandomState.choice>

In [19]:
# meu universo de opções
dois_grupos = make_array('controle', 'tratamento')

In [24]:
np.random.choice(dois_grupos)

'controle'

In [35]:
np.random.choice(dois_grupos, replace=True, size=10)

array(['tratamento', 'controle', 'controle', 'controle', 'tratamento',
       'tratamento', 'controle', 'tratamento', 'tratamento', 'tratamento'],
      dtype='<U10')

In [36]:
outcomes = np.random.choice(dois_grupos, 10)

In [37]:
outcomes

array(['tratamento', 'tratamento', 'controle', 'tratamento', 'controle',
       'tratamento', 'controle', 'controle', 'controle', 'controle'],
      dtype='<U10')

In [38]:
outcomes == 'controle'

array([False, False,  True, False,  True, False,  True,  True,  True,
        True])

In [40]:
sum(outcomes == 'tratamento')

4

In [41]:
sum(outcomes == 'controle')

6

### Cria nosso dado não viciado

In [43]:
d = np.arange(6) +  1
d

array([1, 2, 3, 4, 5, 6])

### joga o dado 1000 vezes

In [45]:
arr_rolls_1000 = np.random.choice(d, 1000)

In [48]:
# vizualiza o resultado
arr_rolls_1000

array([2, 6, 5, 4, 5, 1, 1, 2, 3, 3, 4, 5, 5, 4, 6, 5, 5, 3, 3, 5, 4, 1,
       4, 6, 4, 2, 6, 2, 1, 5, 3, 3, 1, 6, 6, 6, 1, 3, 5, 3, 5, 4, 5, 4,
       3, 1, 6, 5, 4, 3, 2, 3, 5, 1, 6, 1, 3, 2, 5, 5, 6, 2, 3, 2, 2, 4,
       3, 4, 2, 5, 3, 2, 3, 2, 3, 3, 1, 1, 1, 1, 4, 6, 2, 4, 1, 5, 1, 3,
       2, 4, 6, 1, 6, 1, 5, 4, 5, 2, 5, 6, 6, 2, 4, 4, 6, 6, 5, 1, 3, 5,
       5, 3, 6, 6, 1, 1, 2, 3, 1, 5, 5, 5, 5, 1, 4, 2, 1, 3, 3, 2, 1, 4,
       5, 2, 3, 5, 1, 6, 5, 1, 4, 3, 4, 1, 2, 1, 2, 4, 1, 5, 1, 1, 5, 4,
       1, 4, 2, 2, 6, 3, 2, 6, 4, 3, 6, 3, 5, 4, 6, 3, 1, 3, 4, 5, 6, 6,
       4, 5, 6, 1, 3, 5, 3, 1, 3, 2, 5, 2, 1, 1, 4, 6, 1, 2, 6, 1, 3, 2,
       5, 1, 5, 5, 6, 1, 2, 3, 1, 2, 1, 3, 3, 3, 4, 4, 5, 3, 6, 4, 4, 3,
       5, 6, 2, 2, 4, 2, 4, 6, 1, 3, 1, 3, 1, 5, 1, 5, 1, 1, 4, 6, 2, 3,
       1, 6, 3, 2, 6, 1, 4, 6, 3, 5, 6, 6, 1, 5, 4, 6, 4, 6, 3, 6, 5, 1,
       1, 2, 2, 1, 2, 5, 5, 3, 5, 5, 6, 3, 5, 4, 6, 1, 1, 1, 4, 6, 3, 5,
       6, 4, 1, 5, 3, 2, 1, 5, 3, 1, 4, 2, 6, 2, 5,

In [49]:
# cria uma tabela com os resultados dos dados
tb_dado_1000 = Table().with_column('dado', arr_rolls_1000)
tb_dado_1000

dado
2
6
5
4
5
1
1
2
3
3
... (990 rows omitted)

In [50]:
tb_dado_1000.hist()