In [4]:
import pandas as pd
from datascience import *
import numpy as np

In [9]:
# cria um array com idades
arr_idades = np.arange(9, 60)
arr_idades

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [10]:
tb_idades = Table().with_column('idade', arr_idades)
tb_idades

idade
9
10
11
12
13
14
15
16
17
18
... (41 rows omitted)

### Predicates
#### Predicados na verdade são funções que podem ser passadas no where

In [13]:
ainda_jovem = are.between(35,41)
ainda_jovem

In [14]:
tb_idades.where('idade', ainda_jovem)

idade
35
36
37
38
39
40

### podemos passar um predicate para um apply

In [15]:
# cria outro predicado
adolescente = are.between(12, 16)

In [16]:
tb_idades.apply(adolescente, 'idade')

array([False, False, False,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [17]:
tb_idades.where('idade', adolescente)

idade
12
13
14
15

### Random Selection

In [18]:
# with replacenent (independent events)
np.random.choice

<function RandomState.choice>

In [19]:
# meu universo de opções
dois_grupos = make_array('controle', 'tratamento')

In [24]:
np.random.choice(dois_grupos)

'controle'

In [35]:
np.random.choice(dois_grupos, replace=True, size=10)

array(['tratamento', 'controle', 'controle', 'controle', 'tratamento',
       'tratamento', 'controle', 'tratamento', 'tratamento', 'tratamento'],
      dtype='<U10')

In [36]:
outcomes = np.random.choice(dois_grupos, 10)

In [37]:
outcomes

array(['tratamento', 'tratamento', 'controle', 'tratamento', 'controle',
       'tratamento', 'controle', 'controle', 'controle', 'controle'],
      dtype='<U10')

In [38]:
outcomes == 'controle'

array([False, False,  True, False,  True, False,  True,  True,  True,
        True])

In [40]:
sum(outcomes == 'tratamento')

4

In [41]:
sum(outcomes == 'controle')

6

### creates a die

In [43]:
d = np.arange(6) +  1
d

array([1, 2, 3, 4, 5, 6])